---
version: '3.7'

services:

    es:
        container_name: tla-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
            discovery.type: single-node
            xpack.security.enabled: "false"
            ingest.geoip.downloader.enabled: "false"
        ports:
            - ${ES_PORT:-9200}:9200
        restart: unless-stopped


    populate:
        container_name: tla-ingest
        depends_on:
            - es
        build:
            context: https://github.com/thesaurus-linguae-aegyptiae/tla-es.git#master
        environment:
            - ES_HOST=es
            - ES_PORT=9200
            - SAMPLE_URL=https://nubes.bbaw.de/s/Ls7betyCtcTJzgm/download/full-entschlackt.tar.gz
        command: "ingest"


    backend:
        container_name: tla-backend
        depends_on:
            - populate
        build:
            context: https://github.com/thesaurus-linguae-aegyptiae/tla-es.git#master
        environment:
            - ES_HOST=es
            - ES_PORT=9200
        ports:
            - ${BACKEND_PORT:-8090}:8090
        restart: unless-stopped


    frontend:
        container_name: tla-web
        build:
            context: .
        environment:
            - BACKEND_PORT=8090
            - BACKEND_HOST=backend
            - JQUERY_VERSION
            - COOKIEJS_VERSION
            - FONTAWESOME_VERSION
            - BOOTSTRAP_VERSION
        ports:
            - ${LISTEN_PORT:-9005}:9005
        restart: unless-stopped

...
