---
version: '3.7'

services:

    es:
        container_name: tla-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
            discovery.type: single-node
            http.port: 9201
        ports:
            - 9201:9201
        stdin_open: true
        tty: true
        restart: unless-stopped


    populate:
        container_name: tla-ingest
        depends_on:
            - es
        build:
            context: https://github.com/thesaurus-linguae-aegyptiae/tla-es.git#server  
        environment:
            - ES_HOST=es
            - ES_PORT=9201
            - SAMPLE_URL=https://sandbox.zenodo.org/record/715217/files/tla-data.tar.gz
        tty: true
        command: "ingest"


    backend:
        container_name: tla-backend
        build:
            context: https://github.com/thesaurus-linguae-aegyptiae/tla-es.git#server  
        environment:
            - ES_HOST=es
            - ES_PORT=9201
        ports:
            - ${BACKEND_PORT:-9000}:9000
        tty: true
        restart: unless-stopped


    frontend:
        container_name: tla-web
        build:
            context: .
        environment:
            - BACKEND_PORT=9000
            - BACKEND_HOST=backend
            - JQUERY_VERSION
            - COOKIEJS_VERSION
            - FONTAWESOME_VERSION
            - BOOTSTRAP_VERSION
        ports:
            - ${LISTEN_PORT:-9100}:9100
        tty: true
        restart: unless-stopped

...
