---

server:
    port : 9100
    tomcat:
        relaxed-query-chars: ['[', ']']
    error:
        whitelabel:
            enabled: false

tla:
    name: Thesaurus Linguae Aegyptiae
    baseurl: https://tlapublic.bbaw.de
    backend-url: http://tlapublic.bbaw.de:${BACKEND_PORT:9000}
    editorials:
        path: pages
        lang-default: en
    l10n:
        - en
        - de

    link-formatters:
        aaew:
            type-formats:
                hieratic_hieroglyphic: http://aaew.bbaw.de/tla/servlet/GetWcnDetails?u=guest&f=0&l=0&wn={id}&db=0
                demotic: http://aaew.bbaw.de/tla/servlet/GetWcnDetails?u=guest&f=0&l=0&wn={id}&db=1
            id-pattern: ^-?[1-9][0-9]*$
        aegyptiaca:
            default-format: https://aegyptiaca.uni-muenster.de/Record/{id}
        bm:
            type-formats:
                object: https://www.britishmuseum.org/collection/object/{id}
        dwl:
            default-format: https://www.dwl.aegyptologie.lmu.de/suche.php?nummer={id}
        dza:
            type-formats:
                hieratic_hieroglyphic: http://aaew.bbaw.de/tla/servlet/DzaBrowser?u=guest&f=0&l=0&wn={id}
        cfeetk:
            default-format: http://sith.huma-num.fr/vocable/{id}
            id-pattern: ^[1-9][0-9]*$
        oeb:
            default-format: http://oeb.griffith.ox.ac.uk/oeb_entry.aspx?item={id}
        trismegistos:
            default-format: https://www.trismegistos.org/{type}/{id}
            id-pattern: ^[1-9][0-9]*$
            type-pattern: ^(text|collection|place)$
        topbib:
            type-formats:
                griffith: http://topbib.griffith.ox.ac.uk/dtb.html?topbib={id}
                thot: http://thot.philo.ulg.ac.be/concept/{id}
        thot:
            default-format: http://thot.philo.ulg.ac.be/concept/{id}
        met:
            default-format: http://projetrosette.info/popup.php?Id=1004&MET={id}/2&Lang1=EN
        gnd:
            default-format: http://d-nb.info/gnd/{id}
        zdb:
            default-format: https://ld.zdb-services.de/resource/{id}
        wikidata:
            default-format: https://www.wikidata.org/wiki/{id}
        ramses:
            type-formats:
                text: https://ramses.ulg.ac.be/text/legacy/{id}

search:
    config:
        default: lemma

    lemma:
        sort-orders:
            - sortKey_asc
            - sortKey_desc
            - timeSpan.begin_asc
            - timeSpan.begin_desc
            - timeSpan.end_asc
            - timeSpan.end_desc
        hideable1-lemma-properties:
            hieroglyphs: []
            lemma-id: []
            wordClass: []
        
        hideable2-lemma-properties:  
            attested-timespan: []   
            bibliography: []
           
        showable-properties:
             de: []
             en: []
             fr: []   
        word-classes:
            excl_names: []
            excl_namestitlesepithets: []
            adjective:
                - nisbe_adjective_substantive
                - nisbe_adjective_preposition
            adverb:
                - prepositional_adverb
            substantive:
                - substantive_fem
                - substantive_masc
            interjection: []
            entity_name:
                - animal_name
                - gods_name
                - person_name
                - kings_name
                - place_name
                - org_name
                - artifact_name
            numeral:
                - cardinal
                - ordinal
            particle:
                - particle_enclitic
                - particle_nonenclitic
            preposition: []
            pronoun:
                - demonstrative_pronoun
                - interrogative_pronoun
                - personal_pronoun
                - relative_pronoun
            root: []
            epitheton_title:
                - title
                - epith_god
                - epith_king
            verb:
                - verb_2-lit
                - verb_3-lit
                - verb_4-lit
                - verb_5-lit
                - verb_6-lit
                - verb_2-gem
                - verb_3-gem
                - verb_3-inf
                - verb_4-inf
                - verb_5-inf
                - verb_caus_2-lit
                - verb_caus_3-lit
                - verb_caus_4-lit
                - verb_caus_5-lit
                - verb_caus_2-gem
                - verb_caus_3-gem
                - verb_caus_3-inf
                - verb_caus_4-inf
                - verb_irr

        annotation-types:
            lemma: []
            
    sentence:
        hideable-properties:
            hieroglyphs: []
            switchannotation: 
                - wordclass
                - tlaglossing
                - linguisticglossing
                - tokentranslation
                - wordtokenid    
            translation: []
            dating: []
            texteditor: []

details:
    lemma:
        passport-properties:
            - lemma.main_group.nominal_schenkel
            - lemma.main_group.nominal_osing

---

logging:
    file:
        name: app.log
    level:
        root: DEBUG

spring:
    config:
        activate:
            on-profile: dev
    messages:
          fallback-to-system-locale: true
          basename: messages_en     
    thymeleaf:
        cache: false
        prefix: file:./src/main/resources/templates/
        check-template-location: true
    web:
        resources:
            static-locations:
            - file:./src/main/resources/static/
            - file:./src/main/resources/pages/
            cache:
                period: 0

...
